name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build JAR (and JIB pushes docker image to github)
      run: mvn -B clean compile com.google.cloud.tools:jib-maven-plugin:2.4.0:build -P prod -Duser.timezone=CET -Djib.to.auth.username=jirkapinkas -Djib.to.auth.password=${{ secrets.GH_ACCESS_TOKEN }} --file pom.xml

    - name: Pull image from github and recreate Docker container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          docker pull docker.pkg.github.com/jirkapinkas/java-blog-aggregator-boot/java-blog-aggregator
          docker image prune -f
          docker rm -v -f topjavablogs | true
          docker run --log-opt max-size=10m --log-opt max-file=10 --restart=always -d --name topjavablogs -p 127.0.0.1:8083:8080 -v /hosting/topjavablogs/application.properties:/application.properties --add-host=postgres:185.8.239.196 docker.pkg.github.com/jirkapinkas/java-blog-aggregator-boot/java-blog-aggregator:latest
    - name: Check sitemap
      run: |
        echo "Waiting for 60 seconds ..."
        sleep 60
        echo "... done waiting"
        docker run jirkapinkas/sitemap_validator /check_sitemap/main.py -s "https://www.topjavablogs.com/sitemap.xml" -c 5

